### ISSUE TITLE
--only-go removes .c and .h files which breaks cgo packages

### ISSUE THREAD

**Issue by chancez** [sgotti/glide-vc#10]
I know it's possible to not use this option, but it does cause problems in this case, so it might be worth thinking about how to deal with cgo.

**Comment by sgotti** [comment]
@chancez yeah. I haven't considered the cgo case.

Without doing code analysis what about this plan:
- rename `--only-go` to `--only-source` or `--only-code`
- Also keep all the cgo files under the needed packages. From go docs: `.c`, `.s`,`.S`, `.cc`, `.cpp`, `.cxx`, `.h`, `.hh`, `.hpp`, `.hxx` files.

**Comment by mattfarina** [comment]
To weight in for a moment,
- I like that these conversations are happening here. Yay.
- I'm a fan of attempting to keep go related source. In the documentation that may be worth calling out. I say this because there are edge cases that have been brought to my attention of keeping JavaScript or other languages in the same codebase. I wouldn't try to keep those. If you want that don't use this switch. But, at least note that it's trying to keep Go related source.

**Comment by s-urbaniak** [comment]
I'd vote to make the set (whitelist) of valid suffixes configurable via command line switch, we have the edge case to vendor https://github.com/appc/spec/blob/master/ace/image_manifest_main.json.in.

**Comment by chancez** [comment]
@s-urbaniak Easy enough in a follow up PR I'd say, but I'd like to get this in first as it's making this tool unusable for packages depending on cgo.
