### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattfarina** [sgotti/glide-vc#3]
What license is this available under? Without a license it's technically not open source. Glide itself is under the MIT.

**Comment by sgotti** [comment]
@mattfarina Uh, I putted it online too fast and forgot the license! In other projects I used the apache2 license (https://github.com/sorintlab/stolon) just because it was happily used also in other projects I was contributing like https://github.com/coreos/rkt.

But, for this one I'm ok with the MIT license so I'll commit it.

P.S. I just noticed that the Glide's LICENSE file is missing the `The MIT License (MIT)` first line.

**Comment by sgotti** [comment]
@mattfarina Added MIT License as Glide. If in future you'd like to integrate it in glide, I'll be happy to do it and there should be no problem. Thanks!
